[workspace]
authors = ["Guilherme Sena <gbrandine@pacificbiosciences.com>"]
channels = ["conda-forge", "bioconda", "anaconda"]
name = "smn-homology"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pylint = "*"
numpy = "*"

[pypi-dependencies]
scikit-learn = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
scipy = "*"

[system-requirements]
linux = "3.1.0"
cuda = "12.8"
